// src/adapters/web/gui/flavours/react/NewsPanel.js
import "@babel/polyfill";
import React from "react";
import { Transition, CSSTransition } from 'react-transition-group';

class NewsPanel extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
        source: [],
    };
  }

  async componentDidMount() {
    this.props.application.on(this.props.loadEvents, 
        e => this.setState({ source: e.items }));

    this.props.application.on(this.props.filterEvents, 
        e => this.setState({ source: this.state.source.filter(it => it.id != e.id) }));

    this.setState({ source: await this.props.application[this.props.useCase].list() });
  }

  trim (text, count) {
    return `${text.substring(0, count)}${text.length > count ? '...' : ''}`;
  }

  render() {

    const defaultProps = {
        showAge:        true,
        showHost:       true,
        allowBookmark:  true,
        allowSnooze:    false,
        filterEvents: [],
        loadEvents: []
    }

    const props = {...defaultProps, ...this.props };

    return (
      <div id={props.id} className="bs-component">
        <div className="title">{props.title} <span className='lastUpdated'></span></div>
        <ol className="items list-group">
            {this.state.source.map((newsItem, i) => 
              <li className={`item list-group-item ${newsItem.deleted ? 'deleted': ''}`} id={`news-${newsItem.id}`} key={newsItem.id}>
                  <div className="item-body">
                    <div className="lead">
                      <a href={newsItem.url} className="title" title={newsItem.title}>{this.trim(newsItem.title)}</a>
                      <CSSTransition
                        in={true}
                        timeout={{ appear: 500*i }}
                        classNames='fade'
                        appear
                        >
                            <div className="meta">
                            {props.showAge &&
                                <span className="age">{newsItem.ageSince(props.application.now())}</span>
                            }
                            {props.showHost &&
                                <span className="host">{newsItem.host}</span>
                            }
                            </div>
                        </CSSTransition>
                    </div>
                  
                  <div className="controls">
                    {props.allowBookmark &&
                        <a
                            href="#"
                            onClick={() => application.bookmarks.add(`${newsItem.id}`)}
                            className="bookmark btn btn-success">
                            bookmark
                        </a> 
                    }
                    
                    {props.allowSnooze &&
                        <a
                            href="#"
                            onClick={() => application[props.useCase].snooze(`${newsItem.id}`)}
                            className="snooze btn btn-warning"
                            title={`Snooze item with id '${newsItem.id}'`}>
                            snooze
                        </a> 
                    }

                    {!newsItem.deleted &&
                        <a
                            href="#"
                            onClick={() => application[props.useCase].delete(`${newsItem.id}`)}
                            className="del btn btn-danger"
                            title={`Delete item with id '${newsItem.id}'`}>
                            delete
                        </a>
                    }
                  </div>
                </div>
              </li>
            )}
        </ol>
    </div>
    );
  }
}

export default NewsPanel;

// src/adapters/web/gui/flavours/svelte/src/NewsPanel.svelte
<script>
    import { fade, fly } from 'svelte/transition';

    export let id               = 'unknown';
    export let title            = 'Default title';
    export let useCase          = 'default';
    export let allowSnooze      = true;
    export let allowBookmark    = true;
    export let source           = [];
    export let load             = () => Promise.resolve();
    export let showHost         = true;
    export let showAge          = true;

    const trim = (text, count) => {
        const ellipsis = text.length > count ? '...' : '';
        return `${text.substring(0, count)}${ellipsis}`;
    }
</script>

<div id="{id}" class="bs-component">
    <div class="title">{title} {#await load()}<span class="loading" transition:fade>Loading...</span>{/await}</div>
    <ol class="items list-group">
        {#each source as newsItem} <!-- https://svelte.dev/docs#class_name -->
            <li class:deleted={newsItem.deleted} class='item list-group-item' id="news-{newsItem.id}" 
                in:fade|local="{{duration:1000}}" out:fade|local="{{duration:0}}">
            <div class="item-body">
                <div class="lead">
                    <a href={newsItem.url} class="title" title="{newsItem.title}">{trim(newsItem.title)}</a>
                    <div class="meta">
                        {#if showAge}
                            <span class="age">{newsItem.ageSince(window.application.now())}</span>
                        {/if}
                        {#if showHost}
                            <span class="host">{newsItem.host}</span>
                        {/if}
                    </div>
                </div>
                <div class="controls">
                    {#if allowBookmark}
                        <a
                            href="javascript:application.bookmarks.add('{newsItem.id}')"
                            class="bookmark btn btn-success">
                            bookmark
                        </a>
                    {/if}

                    {#if allowSnooze}
                        <a
                            href="javascript:application.{useCase}.snooze('{newsItem.id}')"
                            class="snooze btn btn-warning"
                            title="Snooze item with id '{newsItem.id}'">
                            snooze
                        </a>
                    {/if}
                    {#if newsItem.deleted == false}
                        <a
                            href="javascript:application.{useCase}.delete('{newsItem.id}')"
                            class="del btn btn-danger"
                            title="Delete item with id '{newsItem.id}'">
                            delete
                        </a>
                    {/if}
                </div>
            </div>
            </li>
        {/each}
    </ol>
</div>
