// src/adapters/web/gui/flavours/svelte-smui/src/NewsPanel.svelte
<script>
    import { fade, fly } from 'svelte/transition';
    import DataTable, {Head, Body, Row, Cell} from '@smui/data-table';

    export let application      = {};
    export let id               = 'unknown';
    export let title            = 'Default title';
    export let useCase          = 'default';
    export let allowSnooze      = true;
    export let allowBookmark    = true;
    export let source           = [];
    export let load             = () => Promise.resolve();
    export let showHost         = true;
    export let showAge          = true;

    const trim = (text, count) => {
        const ellipsis = text.length > count ? '...' : '';
        return `${text.substring(0, count)}${ellipsis}`;
    }

    const snooze = id => application[useCase].snooze(id);
</script>

<DataTable id="{id}" table$aria-label="Bookmarks">
    <Head>
      <Row>
        <Cell colspan="4">{title} {#await load()}<span class="loading" transition:fade>Loading...</span>{/await}</Cell>
      </Row>
    </Head>
    <Body>
      {#each source as newsItem, i} <!-- https://svelte.dev/docs#class_name -->
        <Row>
          <Cell>
          {i+1}
          </Cell>
          <Cell style="min-width: 75px">
            <a href={newsItem.url} class="title" title="{newsItem.title}">{trim(newsItem.title, 50)}</a>
            <div class="meta">
                {#if showAge}
                    <span class="age">{newsItem.ageSince(window.application.now())}</span>
                {/if}
                {#if showHost}
                    <span class="host">{newsItem.host}</span>
                {/if}
            </div>
          </Cell>
          <Cell>
           {#if allowBookmark}
              <a
                  href="javascript:application.bookmarks.add('{newsItem.id}')"
                  class="bookmark btn btn-success">
                  bookmark
              </a>
            {/if}

            {#if allowSnooze}
                <a
                    on:click={() => snooze(newsItem.id)} 
                    href={"#"} 
                    class="snooze btn btn-warning"
                    title="Snooze item with id '{newsItem.id}'">
                    snooze
                </a>
            {:else}
                <a
                    href={"#"}
                    class="snooze btn btn-warning disabled"
                    title="Snooze not allowed on this item">
                    snooze
                </a>    
            {/if}
                    
            {#if newsItem.deleted == false}
                <a
                    href="javascript:application.{useCase}.delete('{newsItem.id}')"
                    class="del btn btn-danger"
                    title="Delete item with id '{newsItem.id}'">
                    delete
                </a>
            {/if}
          </Cell>
        </Row>
        {/each}
    </Body>
  </DataTable>

// src/adapters/web/gui/flavours/vue/NewsPanel.vue
<script>
    export default {
        props: { 
            id:             { type: String }, 
            useCase:        { type: String }, 
            title:          { type: String },
            source:         { type: Array   , default: [] }, 
            showAge:        { type: Boolean , default: true }, 
            showHost:       { type: Boolean , default: true },
            allowBookmark:  { type: Boolean , default: true },
            allowSnooze:    { type: Boolean , default: true },
            application:    { type: Object },
        },
        methods: {
            trim(text, count) {
                const ellipsis = text.length > count ? '...' : '';
                return `${text.substring(0, count)}${ellipsis}`;
            },
            bookmarkLink(newsItem) {
                return `javascript:application.bookmarks.add('${newsItem.id}')`;
            },
            snoozeLink(useCase, newsItem) {
                return `javascript:application.${useCase}.snooze('${newsItem.id}')`;
            },
            deleteLink(useCase, newsItem) {
                return `javascript:application.${useCase}.delete('${newsItem.id}')`;
            },
            newsItemId(newsItem) {
                return `news-${newsItem.id}`;
            }
        },
    };
</script>

<style scoped>
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}
</style>

<template>
    <div :id="id" class="bs-component">
        <div class="title">{{ title }}</div>
        <transition-group name="fade" tag="ol" class="items list-group">
        <!-- <ol class="items list-group"> -->
            <li v-for="newsItem in source" :key="newsItem.id" class='item list-group-item' v-bind:class="{deleted: newsItem.deleted}" :id=newsItemId(newsItem)>
                <transition name="fade">
                    <div class="item-body">
                        <div class="lead">
                            <a :href="newsItem.url" class="title" :title="newsItem.title">{{ trim(newsItem.title) }}</a>
                            <div class="meta">
                                <span v-if="showAge" class="age">{{ newsItem.ageSince(application.now()) }}</span>
                                <span v-if="showHost" class="host">{{ newsItem.host }}</span>
                            </div>
                        </div>
                        <div class="controls">
                            <a v-if="allowBookmark"
                                :href=bookmarkLink(newsItem)
                                class="bookmark btn btn-success">
                                bookmark
                            </a>
                            <a v-if="allowSnooze"
                                :href=snoozeLink(useCase,newsItem) 
                                class="snooze btn btn-warning"
                                title="Snooze item">
                                snooze
                            </a>
                            <a v-if="!newsItem.deleted"
                                :href=deleteLink(useCase,newsItem) 
                                class="del btn btn-danger"
                                title="Delete item">
                                delete
                            </a>
                        </div>    
                    </div>
                </transition>
            </li>
        </transition-group>
    </div>
</template>
